### ISSUE TITLE
dist.zip gave the following error for accessing /tmp 

### ISSUE THREAD

**Issue by wumingzhang** [alexschultz/ReadToMe#2]
Dear Alex, I am testing this for deeplens for a demo and ran into some trouble...

I am sure that /tmp is allowed to read and write, however lambda is unable to access it. Any idea?

[2018-11-17T14:20:23.019-05:00][INFO]-readToMeLambda.py:56,exception occurred!
[2018-11-17T14:20:23.027-05:00][INFO]-traceback.py:13,Traceback (most recent call last):

[2018-11-17T14:20:23.039-05:00][INFO]-traceback.py:13,  File "/lambda/readToMeLambda.py", line 43, in firstR
unFunc

[2018-11-17T14:20:23.061-05:00][INFO]-traceback.py:13,    speak.playAudioFile(os.path.join('staticfiles', 'intro.mp3'))

[2018-11-17T14:20:23.067-05:00][INFO]-traceback.py:13,  File "/lambda/speak.py", line 36, in playAudioFile

[2018-11-17T14:20:23.077-05:00][INFO]-traceback.py:13,    play(song)

[2018-11-17T14:20:23.083-05:00][INFO]-traceback.py:13,  File "/lambda/pydub/playback.py", line 46, in play

[2018-11-17T14:20:23.098-05:00][INFO]-traceback.py:13,    _play_with_ffplay(audio_segment)

[2018-11-17T14:20:23.106-05:00][INFO]-traceback.py:13,  File "/lambda/pydub/playback.py", line 19, in _play_with_ffplay

[2018-11-17T14:20:23.113-05:00][INFO]-traceback.py:13,    subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", f.name])

[2018-11-17T14:20:23.13-05:00][INFO]-traceback.py:13,  File "/usr/lib/python2.7/tempfile.py", line 440, in __exit__

[2018-11-17T14:20:23.139-05:00][INFO]-traceback.py:13,    self.close()

[2018-11-17T14:20:23.145-05:00][INFO]-traceback.py:13,OSError: [Errno 2] No such file or directory: '/tmp/tmpQebKWI.wav'

[2018-11-17T14:20:23.166-05:00][ERROR]-threading.py:814,Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/lambda/readToMeLambda.py", line 30, in run
    os.mkfifo(fifo_path)
OSError: [Errno 2] No such file or directory

[2018-11-17T14:20:41.967-05:00][INFO]-readToMeLambda.py:113,starting lambda
[2018-11-17T14:20:41.973-05:00][INFO]-readToMeLambda.py:115,first run True
[2018-11-17T14:20:41.975-05:00][INFO]-readToMeLambda.py:40,first run

**Comment by alexschultz** [comment]
Can you confirm this is what your greengrass setup looks like
![greengrass](https://user-images.githubusercontent.com/1521763/48677838-da73e080-eb48-11e8-9a0b-8a12024432eb.png)

**Comment by alexschultz** [comment]
please reopen if you still need help
